version: '2'

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    env_file:
      - .env.dev
    restart: always
    networks:
      - internal-net
    volumes:
      - postgres_data:/bitnami/postgresql

  api:
    build:
      context: api
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    restart: always
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_PORT=5432
    networks:
      - internal-net
    ports:
      - "8080:80"
    volumes:
      - "${PWD}/keys_config.dev.json:/app/keys_config.json:ro"
      - "${PWD}/dev_keys:/app/dev_keys:ro"


networks:
  internal-net:
    driver: bridge


volumes:
  postgres_data: