[tool.isort]
profile = "black"
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
no_lines_before = "LOCALFOLDER"

[tool.black]
target-version = ['py310']
include = '\.pyi?$'

[tool.pytest.ini_options]
minversion = "7.0"
pythonpath = "api/src"
testpaths = [
    "api/tests"
]